#!/usr/bin/bash
set -e

#
## FUNCTIONS
#

is_ssh_enabled() {
	sshEnabled=$(cat ${CRATE_DIR}/config.json | jq -r '.ssh.enabled') || \
		(${SYNCTROPY_UTILS} error "Failed to read/parse crate configuration file." && \
		exit 1)

	if [ "${sshEnabled}" = "true" ]; then
		return 0
	elif [ "${sshEnabled}" = "false" ]; then
		return 1
	else
		# Invalid configuration
		${SYNCTROPY_UTILS} error "Could not determine if SSH is enabled in crate configuration file"
		exit 1
	fi
}

#
##
#

if is_ssh_enabled; then
	${SYNCTROPY_UTILS} sshagent-stop ${CRATE_TEMP_DIR} || \
		(${SYNCTROPY_UTILS} error "Failed to stop SSH agent" && \
		exit 1)
else
	${SYNCTROPY_UTILS} attention "SSH is disabled in crate configuration"
fi

exit 0
